return
{
    setting={
        title="Setting",
        game="Game",
        volume="Volume",
        graphics="Graphics",
        control="Control",
        quit="Quit"

    },
    game={
        title="Game",
        options={
            language={
                mode="choice",
                title="language",
                choices={"English","中文"},
                value=2,
                default_value=2
            },
            default={
                mode="buttom",
                title="default"
            },
            yes={
                mode="buttom",
                title="yes"
            }
        }
    },
    volume={
        title="fdsfdsf",
        options={
            master_volume={
                mode="bar",
                title="Master Volume",
                value=1.0,
                default_value=1.0
            },
            music_volume={
                mode="bar",
                title="Music Volume",
                value=1.0,
                default_value=1.0
            },
            sfx_volume={
                mode="bar",
                title="SFX Volume",
                value=1.0,
                default_value=1.0
            },
            default={
                mode="buttom",
                title="Default"
            },
            yes={
                mode="buttom",
                title="Yes"
            }
        }
    },
    graphics={
        title="Graphics",
        options={
            resolution={
                mode="choice",
                title="resolution",
                choices={"1920x1080","1260x720","640*360"},
                value=1.0,
                default_value=1.0
            },
            window_mode={
                mode="choice",
                title="window_mode",
                choices={"fullscreen","windowed"},
                value=1.0,
                default_value=1.0
            },
            vsync={
                mode="choice",
                title="vsync",
                choices={"ON","OFF"},
                value=1.0,
                default_value=1.0
            },
            default={
                mode="buttom",
                title="Default"
            },
            yes={
                mode="buttom",
                title="Yes"
            }
        }
    },
    control={
        title="Control",
        options={
            up={
                mode="control",
                title="up",
                value="w",
                default_value="w"
            },
            down={
                mode="control",
                title="down",
                value="s",
                default_value="s"
            },
            left={
                mode="control",
                title="left",
                value="a",
                default_value="a",
            },
            right={
                mode="control",
                title="right",
                value="d",
                default_value="d"
            },
            shoot={
                mode="control",
                title="shoot",
                value="j",
                default_value="j"
            },
            skill={
                mode="control",
                title="skill",
                value="k",
                default_value="k"
            },
            slow={
                mode="control",
                title="slow",
                value="l",
                default_value="l"
            },
            default={
                mode="buttom",
                title="Default"
            },
            yes={
                mode="buttom",
                title="Yes"
            }
        }
    }
}